; Smartwatch IoT — ESP32 + ThingsBoard (Trabalho Final FSE)
[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.partitions = default.csv
build_flags =
    -DCORE_DEBUG_LEVEL=3

