idf_component_register(SRCS "main.cpp"
                            "app_state.cpp"
                            "buzzer.cpp"
                            "display_ui.cpp"
                            "heart_rate.cpp"
                            "imu_sensor.cpp"
                            "inputs.cpp"
                            "network.cpp"
                            "mqtt_client.c"
                            "platform_esp32_idf.c"
                            "mqtt_outbox.c"
                            "mqtt_msg.c"
                       INCLUDE_DIRS "." "../include"
                       REQUIRES esp_adc driver esp_driver_gpio esp_wifi esp_event nvs_flash tcp_transport esp-tls http_parser)
